# cask_args appdir: '/Applications'

tap 'homebrew/bundle'
# tap 'homebrew/services'
# tap 'homebrew/cask-fonts'
tap 'heroku/brew'

brew 'awscli'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'git'
brew 'grc'
brew 'heroku'
brew 'hub'
brew 'nodenv'
brew 'node-build'
brew 'parallel'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'ruby-build'
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'

# Ruby deps
# https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
# brew 'openssl@3'
# brew 'readline'
# brew 'libyaml'
# brew 'gmp'

# cask '1password'
# cask 'backblaze'
# cask 'firefox'
# cask 'google-chrome'
# cask 'iterm2'
# cask 'spotify'
# cask 'sublime-text'

# cask 'font-noto-mono'
# cask 'font-inconsolata'
# cask 'font-open-sans'
# cask 'font-source-code-pro'
# cask 'font-source-sans-pro'
