cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/fonts'
tap 'heroku/brew'

brew 'awscli'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'git'
brew 'grc'
brew 'heroku'
brew 'hub'
brew 'nodenv'
brew 'node-build'
brew 'openssl'
brew 'parallel'
brew 'readline'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'ruby-build'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'airfoil'
cask 'backblaze'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'spotify'
cask 'sublime-text'

cask 'font-noto-mono'
cask 'font-inconsolata'
cask 'font-open-sans'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
