cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/fonts'

brew 'coreutils'
brew 'grc'
brew 'heroku'
brew 'hub'
brew 'node'
brew 'openssl'
brew 'postgresql', restart_service: :changed
brew 'readline'
brew 'redis', restart_service: :changed
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'vim'
brew 'zsh'

cask '1password'
cask 'airfoil'
cask 'atom'
cask 'dropbox'
cask 'github-desktop'
cask 'google-chrome'
cask 'harvest'
cask 'hyper'
cask 'imageoptim'
cask 'iterm2'
cask 'paw'
cask 'slack'
cask 'spotify'
cask 'sublime-text'

cask 'font-inconsolata'
cask 'font-open-sans'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
